************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q2gBornNT(ONE,TWO,THREE,FOUR,FIVE,
     >                                       SIX)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 2D0 * XNc2/(XNc2 - 1D0)
C      X = 0D0

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*conjg(TEMP1) + TEMP2*conjg(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0
      ENDDO

      ENDDO

      PSI2q2gBornNT = XNu*PSI(1) + XNd*PSI(2)
      PSI2q2gBornNT = 4d0*(XNc2-1D0)**2/XNc*PSI2q2gBornNT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

      END

************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q2gBornINT(ONE,TWO,THREE,FOUR,FIVE,
     >                                        SIX,I)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI,XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 2D0 * XNc2/(XNc2 - 1D0)
C      X = 0D0

C u type: I = 1
C d type: I = 2

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      ENDDO

      PSI2q2gBornINT = PSI
      PSI2q2gBornINT = 4d0*(XNc2-1D0)**2/XNc*PSI2q2gBornINT / 4d0 / 2d0

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1

      END
************************************************************************
************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q2gBornNTCF2(ONE,TWO,THREE,FOUR,
     >                                          FIVE,SIX)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 0D0

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

c      write(6,*)'PSI = ',(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
c     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

c      write(6,*)'PSI = ',(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
c     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

c      write(6,*)'PSI = ',(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
c     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

c      write(6,*)'PSI = ',(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
c     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0
c      goto 222

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I)
     >  + (TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >  + (2D0 - X) * (TEMP1*CONJG(TEMP2) + CONJG(TEMP1)*TEMP2)/2D0
      ENDDO

      ENDDO

c 222  PSI(2) = 0d0
c      write(6,*)'PSI(1)4 = ',PSI(1)

      PSI2q2gBornNTCF2 = XNu*PSI(1) + XNd*PSI(2)
      PSI2q2gBornNTCF2 = 4d0*(XNc2-1D0)**2/XNc*PSI2q2gBornNTCF2

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

      END

************************************************************************
************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q2gBornNT2V(ONE,TWO,THREE,FOUR,FIVE,
     >                                         SIX,VPP,VPM,VMP,VMM)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) PSI(2),qgA60,C(2,2,2),TEMP1,TEMP2,TEMP3,TEMP4
     >          ,VPP,VPM,VMP,VMM
     >          ,PSI2q2gBornNTPP,PSI2q2gBornNTPM
     >          ,PSI2q2gBornNTMP,PSI2q2gBornNTMM
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 2D0 * XNc2/(XNc2 - 1D0)

C u type: I = 1
C d type: I = 2

C
C Polarisation: G2 ++ 
C

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      ENDDO

      PSI2q2gBornNTPP = XNu*PSI(1) + XNd*PSI(2)
c      write(6,*)PSI2q2gBornNTPP

C
C Polarisation: G2 +- 
C

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      ENDDO

      PSI2q2gBornNTPM = XNu*PSI(1) + XNd*PSI(2)
c      write(6,*)PSI2q2gBornNTPM

C
C Polarisation: G2 -+ 
C

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)
c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)TEMP1,TEMP2,TEMP3,TEMP4
c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )
c      write(6,*)

      ENDDO

      ENDDO

      PSI2q2gBornNTMP = XNu*PSI(1) + XNd*PSI(2)
c      write(6,*)PSI2q2gBornNTMP

C
C Polarisation: G2 -- 
C

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I)
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      ENDDO

      PSI2q2gBornNTMM = XNu*PSI(1) + XNd*PSI(2)
c      write(6,*)PSI2q2gBornNTMM

C
C T_h1,h2 * V_h1,h2
C

      PSI2q2gBornNT2V = PSI2q2gBornNTPP * VPP
     >                 +PSI2q2gBornNTPM * VPM
     >                 +PSI2q2gBornNTMP * VMP
     >                 +PSI2q2gBornNTMM * VMM

      PSI2q2gBornNT2V = 4d0*(XNc2-1D0)**2/XNc*PSI2q2gBornNT2V

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

      END

************************************************************************
************************************************************************

      SUBROUTINE qgA6treeNT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IMPLICIT NONE

C PPPH5 -> 1+,2+,3+,H5
C MPPH5 -> 1-,2+,3+,H5
C PMMH5 -> 1+,2-,3-,H5
C MMMH5 -> 1-,2-,3-,H5
C PMPH5 -> 1+,2-,3+,H5
C MMPH5 -> 1-,2-,3+,H5
C PPMH5 -> 1+,2+,3-,H5
C MPMH5 -> 1-,2+,3-,H5
C IHEL5 = 1 for 5+
C IHEL5 = 2 for 5-

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5
      COMPLEX(KIND(1D0)) OUT,A(11,11),B(11,11)
      COMPLEX(KIND(1D0)) qggqbA60PPPMNT,qggqbA60PMPMNT
     >          ,qggqbA60PPMMNT,qggqbA60PMMMNT
      COMMON /SPINORPRODUCTS/ A,B

      ENTRY qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PPPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,A,B)
      ELSE
       OUT = qggqbA60PPPMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,A,B)
      ENDIF
      RETURN

      ENTRY qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PPPMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,B,A)
      ELSE
       OUT = qggqbA60PPPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,B,A)
      ENDIF
      RETURN

      ENTRY qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PMMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,A,B)
      ELSE
       OUT = qggqbA60PMMMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,A,B)
      ENDIF
      RETURN

      ENTRY qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PMMMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,B,A)
      ELSE
       OUT = qggqbA60PMMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,B,A)
      ENDIF
      RETURN

      ENTRY qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PPMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,A,B)
      ELSE
       OUT = qggqbA60PPMMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,A,B)
      ENDIF
      RETURN

      ENTRY qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PPMMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,B,A)
      ELSE
       OUT = qggqbA60PPMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,B,A)
      ENDIF
      RETURN

      ENTRY qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PMPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,A,B)
      ELSE
       OUT = qggqbA60PMPMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,A,B)
      ENDIF
      RETURN

      ENTRY qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA60PMPMNT(ONE,TWO,THREE,FOUR,SIX,FIVE,B,A)
      ELSE
       OUT = qggqbA60PMPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,B,A)
      ENDIF
      RETURN

      END

************************************************************************
************************************************************************

************************************************************************
************************************************************************
C     COLOR-CORRELATED TREE AMPS (SUMMED OVER HELICITIES)
************************************************************************
************************************************************************

      REAL(KIND(1D0)) FUNCTION Sfunc1NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP1*CONJG(TEMP1)
      ENDDO

      ENDDO

      Sfunc1NT = XNu*PSI(1) + XNd*PSI(2)

      END

************************************************************************

      REAL(KIND(1D0)) FUNCTION Sfunc1INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI,XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = 1
C d type: I = 2

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP1*CONJG(TEMP1)
      ENDDO

      Sfunc1INT = PSI

      END

************************************************************************
      REAL(KIND(1D0)) FUNCTION Sfunc2NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)

      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + TEMP2*CONJG(TEMP2)
      ENDDO

      ENDDO

      Sfunc2NT = XNu*PSI(1) + XNd*PSI(2)

      END

************************************************************************

      REAL(KIND(1D0)) FUNCTION Sfunc2INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI,XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = 1
C d type: I = 2

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)

      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + TEMP2*CONJG(TEMP2)
      ENDDO

      Sfunc2INT = PSI

      END

************************************************************************

      REAL(KIND(1D0)) FUNCTION Sfunc3NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI(I) = PSI(I) + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)
      ENDDO

      ENDDO

      Sfunc3NT = XNu*PSI(1) + XNd*PSI(2)

      END

************************************************************************

      REAL(KIND(1D0)) FUNCTION Sfunc3INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5
      REAL(KIND(1D0)) PSI,XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) qgA60,C(2,2,2),TEMP1,TEMP2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = 1
C d type: I = 2

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI = PSI + (TEMP1*CONJG(TEMP2)+CONJG(TEMP1)*TEMP2)
      ENDDO

      Sfunc3INT = PSI

      END

************************************************************************
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM14NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1NT,Sfunc2NT,Sfunc3NT
      EXTERNAL Sfunc1NT,Sfunc2NT,Sfunc3NT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S2 = Sfunc2NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S3 = Sfunc3NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      CCM14NT = 2D0*(S1+S2+S3)
     >        -X*(2D0*S1+2D0*S2+3D0*S3)
     >        +X**2/2D0*(S1+S2+2D0*S3)

      CCM14NT = -4d0*NC*CF**3/2D0*CCM14NT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM14INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1INT,Sfunc2INT,Sfunc3INT
      EXTERNAL Sfunc1INT,Sfunc2INT,Sfunc3INT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S2 = Sfunc2INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S3 = Sfunc3INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      CCM14INT = 2D0*(S1+S2+S3)
     >        -X*(2D0*S1+2D0*S2+3D0*S3)
     >        +X**2/2D0*(S1+S2+2D0*S3)

      CCM14INT = -4d0*NC*CF**3/2D0*CCM14INT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

c Symmetry factor for the two, identical gluons, average over initial
c state spin states and final convertion to T_R = 1/2
      CCM14INT = CCM14INT/16d0

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM13NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1NT,Sfunc2NT,Sfunc3NT
      EXTERNAL Sfunc1NT,Sfunc2NT,Sfunc3NT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S2 = Sfunc2NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S3 = Sfunc3NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      CCM13NT = X*(S1+S2+S3)
     >        -X**2/2D0*(S2+S3)

      CCM13NT = -4d0*NC*CF**3/2D0*CCM13NT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM13INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1INT,Sfunc2INT,Sfunc3INT
      EXTERNAL Sfunc1INT,Sfunc2INT,Sfunc3INT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S2 = Sfunc2INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S3 = Sfunc3INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      CCM13INT = X*(S1+S2+S3)
     >        -X**2/2D0*(S2+S3)

      CCM13INT = -4d0*NC*CF**3/2D0*CCM13INT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

c Symmetry factor for the two, identical gluons, average over initial
c state spin states and final convertion to T_R = 1/2
      CCM13INT = CCM13INT/16d0

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM12NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1NT,Sfunc2NT,Sfunc3NT
      EXTERNAL Sfunc1NT,Sfunc2NT,Sfunc3NT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S2 = Sfunc2NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S3 = Sfunc3NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      CCM12NT = X*(S1+S2+S3)
     >        -X**2/2D0*(S1+S3)

      CCM12NT = -4d0*NC*CF**3/2D0*CCM12NT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM12INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1INT,Sfunc2INT,Sfunc3INT
      EXTERNAL Sfunc1INT,Sfunc2INT,Sfunc3INT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S2 = Sfunc2INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S3 = Sfunc3INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      CCM12INT = X*(S1+S2+S3)
     >        -X**2/2D0*(S1+S3)

      CCM12INT = -4d0*NC*CF**3/2D0*CCM12INT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

c Symmetry factor for the two, identical gluons, average over initial
c state spin states and final convertion to T_R = 1/2
      CCM12INT = CCM12INT/16d0

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM34NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX

      REAL(KIND(1D0)) CCM12NT
      EXTERNAL CCM12NT

C NOTE THAT TR = 1/2

      CCM34NT = CCM12NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM34INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I

      REAL(KIND(1D0)) CCM12INT
      EXTERNAL CCM12INT

C NOTE THAT TR = 1/2

      CCM34INT = CCM12INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM24NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX

      REAL(KIND(1D0)) CCM13NT
      EXTERNAL CCM13NT

C NOTE THAT TR = 1

      CCM24NT = CCM13NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM24INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I

      REAL(KIND(1D0)) CCM13INT
      EXTERNAL CCM13INT

C NOTE THAT TR = 1

      CCM24INT = CCM13INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM23NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1NT,Sfunc2NT,Sfunc3NT
      EXTERNAL Sfunc1NT,Sfunc2NT,Sfunc3NT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S2 = Sfunc2NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S3 = Sfunc3NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      CCM23NT = X**2/2D0*(S1+S2)

      CCM23NT = -4d0*NC*CF**3/2D0*CCM23NT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM23INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1INT,Sfunc2INT,Sfunc3INT
      EXTERNAL Sfunc1INT,Sfunc2INT,Sfunc3INT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF

      S1 = Sfunc1INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S2 = Sfunc2INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)
      S3 = Sfunc3INT(ONE,TWO,THREE,FOUR,FIVE,SIX,I)

      CCM23INT = X**2/2D0*(S1+S2)

      CCM23INT = -4d0*NC*CF**3/2D0*CCM23INT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

c Symmetry factor for the two, identical gluons, average over initial
c state spin states and final convertion to T_R = 1/2
      CCM23INT = CCM23INT/16d0

      RETURN

      END
      
************************************************************************
************************************************************************


************************************************************************

      REAL(KIND(1D0)) FUNCTION CCM12NTCF3(ONE,TWO,THREE,FOUR,FIVE,SIX)

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX
      REAL(KIND(1D0)) NC,CF,CA,X,S1,S2,S3

      REAL(KIND(1D0)) Sfunc1NT,Sfunc2NT,Sfunc3NT
      EXTERNAL Sfunc1NT,Sfunc2NT,Sfunc3NT

C NOTE THAT TR = 1

      NC = 3D0
      CA = 2d0*NC
      CF = (NC**2-1D0)/(NC)
      X  = CA/CF
      X = 0D0

      S1 = Sfunc1NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S2 = Sfunc2NT(ONE,TWO,THREE,FOUR,FIVE,SIX)
      S3 = Sfunc3NT(ONE,TWO,THREE,FOUR,FIVE,SIX)

      CCM12NTCF3 = 2D0*(S1+S2+S3)
     >           -X*(2D0*S1+2D0*S2+3D0*S3)
     >           +X**2/2D0*(S1+S2+2D0*S3)

      CCM12NTCF3 = -4d0*NC*CF**3/2D0*CCM12NTCF3

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 2 GLUONS NOT INCLUDED

C---WE EVALUATE <M|T_I T_K|M> WITH TR = 1
C---THE CHANGE TR = 1 -> TR = 1/2 MEANS T_I -> T'_I = 1/SQRT(2) T_I
C---SO TO EVALUATE <M|T_I T_K|M> WITH TR = 1/2
C---<M|T'_I T'_K|M> = 1/2 <M|T_I T_K|M>

      RETURN

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q2gBornV(ONE,TWO,THREE,FOUR,FIVE,SIX,
     >                             QTYPE,M2IJ)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5,QTYPE
      REAL(KIND(1D0)) XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) M2IJ(2,2)
      COMPLEX(KIND(1D0)) TEMP1,TEMP2,TEMP3,TEMP4
      COMPLEX(KIND(1D0)) PSI,qgA60,C(2,2,2),M2PP,M2PM,M2MP,M2MM
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 2D0 * XNc2/(XNc2 - 1D0)

C u type: I = 1
C d type: I = 2
c
c The ordering is 1_{q},2_{g},3_{g},4_{q~}
c PPPHe : 1^+,2^+,3^+
c PPMHe : 1^+,2^+,3^-
c PMPHe : 1^+,2^-,3^+
c MPPHe : 1^-,2^+,3^+
c MPMHe : 1^-,2^+,3^-
c MMPHe : 1^-,2^-,3^+

C
C Polarisation: G2 ++ 
C
      
      I = QTYPE

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      M2PP = PSI

C
C Polarisation: G2 +- 
C

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      M2MP = PSI

C
C Polarisation: G2 -+ 
C

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)
c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)TEMP1,TEMP2,TEMP3,TEMP4
c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )
c      write(6,*)

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)
c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

c      write(6,*)CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
c     > +(2D0 - X)/2D0*( CONJG(TEMP1)*TEMP3 + CONJG(TEMP2)*TEMP4 )

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      M2PM = PSI

C
C Polarisation: G2 -- 
C

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60PMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI = PSI
     > +CONJG(TEMP1)*TEMP2 + CONJG(TEMP3)*TEMP4
     > +(2D0 - X)/2D0*( CONJG(TEMP3)*TEMP2 + CONJG(TEMP1)*TEMP4 )

      ENDDO

      M2MM = PSI

C
C T_h1,h2 * V_h1,h2
C
      M2IJ(2,2) = M2PP
      M2IJ(1,1) = M2MM
      M2IJ(2,1) = M2MP
      M2IJ(1,2) = M2PM
C

      PSI2q2gBornV = M2IJ(1,1) + M2IJ(2,2)

      PSI2q2gBornV = 4d0*(XNc2-1D0)**2/XNc*PSI2q2gBornV
      PSI2q2gBornV = PSI2q2gBornV / 4d0 / 2d0

c Averaging over initial state spin states and 
* symmetry factor for the two gluons:
      M2IJ = 4d0*(XNc2-1D0)**2/XNc*M2IJ / 4d0 / 2d0

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1

      END
      
************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q2gBAKV(ONE,TWO,THREE,FOUR,FIVE,SIX,
     >                                     QTYPE,M2IJ)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,I,IHEL5,QTYPE
      REAL(KIND(1D0)) XNf,XNu,XNd,XNc,XNa,XNc2
      COMPLEX(KIND(1D0)) M2IJ(2,2)
      COMPLEX(KIND(1D0)) TEMP1,TEMP2,TEMP3,TEMP4
      COMPLEX(KIND(1D0)) PSI,qgA60,C(2,2,2),M2PP,M2PM,M2MP,M2MM
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

      XNc2 = XNc**2

C u type: I = QTYPE = 1
C d type: I = QTYPE = 2
c
c The ordering is 1_{q},2_{g},3_{g},4_{q~}
c PPPHe : 1^+,2^+,3^+,4^-
c PPMHe : 1^+,2^+,3^-,4^-
c PMPHe : 1^+,2^-,3^+,4^-
c MPPHe : 1^-,2^+,3^+,4^+
c MPMHe : 1^-,2^+,3^-,4^+
c MMPHe : 1^-,2^-,3^+,4^+

C
C Polarisation: G2 ++ 
C
      
      I = QTYPE

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PPPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)
C
      CALL qgA60PPMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)
C
      CALL qgA60MPPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)
C
      CALL qgA60MPMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)

      ENDDO

      M2PP = PSI

C
C Polarisation: G2 +- 
C

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PPPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)
C
      CALL qgA60PPMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)
C
      CALL qgA60MPPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)
C
      CALL qgA60MPMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)

      ENDDO

      M2MP = PSI

C
C Polarisation: G2 -+ 
C

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PMPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)
C
      CALL qgA60PMMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)
C
      CALL qgA60MMPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)
C
      CALL qgA60MMMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP3 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMPH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP4 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP2) + TEMP3*CONJG(TEMP4))
     >      - (TEMP1 + TEMP3)*CONJG(TEMP2 + TEMP4)

      ENDDO

      M2PM = PSI

C
C Polarisation: G2 -- 
C

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2
      CALL qgA60PMMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PMMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)
C
      CALL qgA60PMPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,2,I)*qgA60
      CALL qgA60PPMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,2,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)
C
      CALL qgA60MMMH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MMMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)
C
      CALL qgA60MMPH5(ONE,TWO,THREE,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP1 = C(IHEL5,1,I)*qgA60
      CALL qgA60MPMH5(ONE,THREE,TWO,FOUR,FIVE,SIX,IHEL5,qgA60)
      TEMP2 = C(IHEL5,1,I)*qgA60
      PSI   = PSI
     >      + XNc2*(TEMP1*CONJG(TEMP1) + TEMP2*CONJG(TEMP2))
     >      - (TEMP1 + TEMP2)*CONJG(TEMP1 + TEMP2)

      ENDDO
C
      M2MM = PSI
C
      M2IJ(1,1) = M2PP
      M2IJ(2,2) = M2MM
      M2IJ(1,2) = M2MP
      M2IJ(2,1) = M2PM
C

      PSI2q2gBAKV = M2IJ(1,1) + M2IJ(2,2)

      PSI2q2gBAKV = (XNc2-1D0)/XNc*PSI2q2gBAKV/2d0

c Averaging over initial state spin states and 
* symmetry factor for the two gluons:
      M2IJ = (XNc2-1D0)/XNc*M2IJ/2d0

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1

      END
