************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q3gBornNT(ONE,TWO,THREE,FOUR,FIVE,
     >                                       SIX,SEVEN)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) qgA70,C(2,2,2),TEMP1,TEMP2,TEMP3,TEMP4,
     >                   TEMP5,TEMP6
      REAL(KIND(1D0)) M0,M1,M2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 2D0 * XNc2/(XNc2 - 1D0)
C      X = 0D0

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

C 1, ++++

      CALL qgA70PPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )
      
c      write(6,*)'PSI = ',PSI

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)'M = ',M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 2, +++-

      CALL qgA70PPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+++-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 3, ++-+

      CALL qgA70PPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++-+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 4, +-++

      CALL qgA70PMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+-++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 5, ++--

      CALL qgA70PPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++--',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 6, +-+-

      CALL qgA70PMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+-+-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 7, +--+

      CALL qgA70PMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+--+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 8, +---

      CALL qgA70PMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+---',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

c      goto 222

C 9, -+++

      CALL qgA70MPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 10, -++-

      CALL qgA70MPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 11, -+-+

      CALL qgA70MPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 12, --++

      CALL qgA70MMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 13, -+--

      CALL qgA70MPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 14, --+-

      CALL qgA70MMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 15, ---+

      CALL qgA70MMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 16, ----

      CALL qgA70MMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

      ENDDO

      ENDDO

      PSI2q3gBornNT = XNu*PSI(1) + XNd*PSI(2)
      PSI2q3gBornNT = 4d0*(XNc2-1D0)**3/XNc2*PSI2q3gBornNT

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 3 GLUONS NOT INCLUDED

      END

c This routine is almost the same as the previous one but there is no
c summation over the flavors the flavor of the quark line can be
c selected with the input parameter I, I = 1 for u-type, while
c I = 2 for d-type.
************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2qf3gBornNT(ONE,TWO,THREE,FOUR,
     >                               FIVE,SIX,SEVEN,I)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,I,IHEL5
      REAL(KIND(1D0)) PSI,XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) qgA70,C(2,2,2),TEMP1,TEMP2,TEMP3,TEMP4,
     >                   TEMP5,TEMP6
      REAL(KIND(1D0)) M0,M1,M2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
      X = 2D0 * XNc2/(XNc2 - 1D0)
C      X = 0D0

      PSI = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

C 1, ++++

      CALL qgA70PPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )
      
c      write(6,*)'PSI = ',PSI

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)'M = ',M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 2, +++-

      CALL qgA70PPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+++-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 3, ++-+

      CALL qgA70PPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++-+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 4, +-++

      CALL qgA70PMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+-++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 5, ++--

      CALL qgA70PPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++--',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 6, +-+-

      CALL qgA70PMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+-+-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 7, +--+

      CALL qgA70PMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+--+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 8, +---

      CALL qgA70PMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+---',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

c      goto 222

C 9, -+++

      CALL qgA70MPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 10, -++-

      CALL qgA70MPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 11, -+-+

      CALL qgA70MPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 12, --++

      CALL qgA70MMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 13, -+--

      CALL qgA70MPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 14, --+-

      CALL qgA70MMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 15, ---+

      CALL qgA70MMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

C 16, ----

      CALL qgA70MMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI = PSI
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

      ENDDO

      PSI2qf3gBornNT = PSI
      PSI2qf3gBornNT = (XNc2-1D0)**3/XNc2*PSI2qf3gBornNT/6d0

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1

      END

************************************************************************

      REAL(KIND(1D0)) FUNCTION PSI2q3gBornNTCF3
     >                (ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN)
      IMPLICIT NONE

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,I,IHEL5
      REAL(KIND(1D0)) PSI(2),XNf,XNu,XNd,XNc,XNa,XNc2,X
      COMPLEX(KIND(1D0)) qgA70,C(2,2,2),TEMP1,TEMP2,TEMP3,TEMP4,
     >                   TEMP5,TEMP6
      REAL(KIND(1D0)) M0,M1,M2
      COMMON /COUPLINGS/ C
     >       /QCD/XNf,XNu,XNd,XNc,XNa

C By SG, using the NT formulae

      XNc2 = XNc**2
C      X = 2D0 * XNc2/(XNc2 - 1D0)
      X = 0D0

C u type: I = 1
C d type: I = 2

      DO I = 1,2
      PSI(I) = 0D0
C IHEL5 = 1 -> veL
C IHEL5 = 2 -> veR
      DO IHEL5 = 1,2

C 1, ++++

      CALL qgA70PPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )
      
c      write(6,*)'PSI = ',PSI

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)'M+ = ',M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 2, +++-

      CALL qgA70PPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+++-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 3, ++-+

      CALL qgA70PPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++-+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 4, +-++

      CALL qgA70PMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+-++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 5, ++--

      CALL qgA70PPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'++--',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 6, +-+-

      CALL qgA70PMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+-+-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 7, +--+

      CALL qgA70PMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PPMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+--+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 8, +---

      CALL qgA70PMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,2,I)*qgA70
      CALL qgA70PMMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,2,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'+---',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

c      goto 222

C 9, -+++

      CALL qgA70MPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'-+++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)'M- = ',M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 10, -++-

      CALL qgA70MPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'-++-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 11, -+-+

      CALL qgA70MPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'-+-+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 12, --++

      CALL qgA70MMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'--++',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 13, -+--

      CALL qgA70MPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'-+--',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 14, --+-

      CALL qgA70MMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'--+-',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 15, ---+

      CALL qgA70MMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMPMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMPH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MPMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'---+',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

C 16, ----

      CALL qgA70MMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP1 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,THREE,FOUR,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP2 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,FOUR,TWO,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP3 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,TWO,FOUR,THREE,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP4 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,THREE,TWO,FOUR,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP5 = C(IHEL5,1,I)*qgA70
      CALL qgA70MMMMH5NT(ONE,FOUR,THREE,TWO,FIVE,SIX,SEVEN,IHEL5,qgA70)
      TEMP6 = C(IHEL5,1,I)*qgA70

      M0 = (TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)
     >   * CONJG(TEMP1 + TEMP2 + TEMP3 + TEMP4 + TEMP5 + TEMP6)

      M2 = TEMP1 * CONJG(TEMP1) + TEMP2 * CONJG(TEMP2)
     >   + TEMP3 * CONJG(TEMP3) + TEMP4 * CONJG(TEMP4)
     >   + TEMP5 * CONJG(TEMP5) + TEMP6 * CONJG(TEMP6)

      M1 = -2D0 * M2
     >   - ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) )
     >   - CONJG(
     >     ( CONJG(TEMP1) * (TEMP4 + TEMP5 - TEMP6)
     >      +CONJG(TEMP2) * (TEMP5 + TEMP6 - TEMP4)
     >      +CONJG(TEMP3) * (TEMP6 + TEMP4 - TEMP5) ) )

      PSI(I) = PSI(I)
     >  + M0 - X/2D0 * (M1 + 2D0 * M0) 
     >  + X**2/4D0 * (M0 + M1 + M2)

c      write(6,*)'----',TEMP1,TEMP2,TEMP3,TEMP4,TEMP5,TEMP6
c      write(6,*)M0,M1,M2
c      write(6,*)PSI,X
c      write(6,*)

      ENDDO

      ENDDO

      PSI2q3gBornNTCF3 = XNu*PSI(1) + XNd*PSI(2)
      PSI2q3gBornNTCF3 = 4d0*(XNc2-1D0)**3/XNc2*PSI2q3gBornNTCF3

C---NORMALISATION OK, 4 PI ALPHA_EM = 4 PI ALPHA_S = 1
C---SYMMETRY FACTOR FOR 3 GLUONS NOT INCLUDED

      END

************************************************************************
************************************************************************

      SUBROUTINE qgA7treeNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IMPLICIT NONE

C IHEL5 = 1 for 6+
C IHEL5 = 2 for 6-

      INTEGER ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5
      COMPLEX(KIND(1D0)) OUT,A(11,11),B(11,11)
      COMPLEX(KIND(1D0)) qggqbA70PPPPMNT,qggqbA70PPPMMNT
     >          ,qggqbA70PPMPMNT,qggqbA70PMPPMNT
     >          ,qggqbA70PPMMMNT,qggqbA70PMPMMNT
     >          ,qggqbA70PMMPMNT,qggqbA70PMMMMNT
      COMMON /SPINORPRODUCTS/ A,B

C 1,  ++++-
C 16, ----+

      ENTRY qgA70PPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PPPPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PPPPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PPPPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PPPPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 2,  +++--
C 15, ---++

      ENTRY qgA70PPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PPPMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PPPMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PPPMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PPPMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 3,  ++-+-
C 14, --+-+

      ENTRY qgA70PPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PPMPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PPMPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PPMPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PPMPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 4,  +-++-
C 13, -+--+

      ENTRY qgA70PMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PMPPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PMPPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PMPPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PMPPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 5,  ++---
C 12, --+++

      ENTRY qgA70PPMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PPMMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PPMMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MMPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PPMMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PPMMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 6,  +-+--
C 11, -+-++

      ENTRY qgA70PMPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PMPMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PMPMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MPMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PMPMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PMPMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 7,  +--+-
C 10, -++-+

      ENTRY qgA70PMMPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PMMPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PMMPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MPPMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PMMPMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PMMPMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

C 8,  +----
C 9,  -++++

      ENTRY qgA70PMMMH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = qggqbA70PMMMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,A,B)
      ELSE
       OUT = qggqbA70PMMMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,A,B)
      ENDIF
      RETURN

      ENTRY qgA70MPPPH5NT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,IHEL5,OUT)
      IF (IHEL5.EQ.2) THEN
       OUT = -qggqbA70PMMMMNT(ONE,TWO,THREE,FOUR,FIVE,SEVEN,SIX,B,A)
      ELSE
       OUT = -qggqbA70PMMMMNT(ONE,TWO,THREE,FOUR,FIVE,SIX,SEVEN,B,A)
      ENDIF
      RETURN

      END

************************************************************************
************************************************************************
